// Generated by CoffeeScript 1.12.5
(function() {
  var CWD, _settings, cli, fs;

  fs = require('fs');

  cli = require('cli');

  _settings = require('./settings');

  CWD = process.cwd();

  module.exports = {
    readPM2MeteorConfig: function() {
      var conf, err;
      conf = null;
      try {
        conf = JSON.parse(fs.readFileSync(_settings.pm2MeteorConfigName, 'utf8'));
      } catch (error) {
        err = error;
        cli.fatal("Error while trying to read pm2-meteor config: " + err.message);
      }
      return conf;
    }
  };

}).call(this);
