// Generated by CoffeeScript 1.12.6
(function() {
  var CWD, _settings, cli, fs, path;

  fs = require('fs');

  cli = require('cli');

  _settings = require('./settings');

  CWD = process.cwd();

  path = require('path');

  module.exports = {
    readPM2MeteorConfig: function() {
      var conf, err;
      conf = null;
      try {
        conf = require(path.resolve(CWD, _settings.tryReadPm2MeteorConfigName));
        return conf;
      } catch (error) {
        err = error;
        return cli.fatal("Error while trying to read pm2-meteor config " + err.message);
      }
    }
  };

}).call(this);
