#! /usr/bin/env node
// Generated by CoffeeScript 1.12.6
(function() {
  var cmds, currentVersion, program;

  program = require('commander');

  cmds = require('./commandList');

  currentVersion = require('../package.json').version;

  program.version("" + currentVersion);

  program.command('init').description("init a pm2-meteor settings file").action(function() {
    return cmds["init"]();
  });

  program.command('deploy').description('deploy your App to the server(s)').option('-r, --reconfig', "Settings have changed and PM2 should reset the env").action(function() {
    return cmds["deploy"](this.reconfig);
  });

  program.command('reconfig').description('deploy only new settings and env vars').action(function() {
    return cmds["reconfig"]();
  });

  program.command('start').description('start your App on the server(s)').action(function() {
    return cmds["start"]();
  });

  program.command('stop').description('stop your App on the server(s)').action(function() {
    return cmds["stop"]();
  });

  program.command('status').description('print the status of your App (nodes)').action(function() {
    return cmds["status"]();
  });

  program.command('generateBundle').description('generates a tarball, containing the Nodejs build and a pm2-env.json file').action(function() {
    return cmds["generateBundle"]();
  });

  program.command('undeploy').description('undeploy your App from the server(s) - DANGEROUS!').action(function() {
    return cmds["undeploy"]();
  });

  program.command('logs').description('stream realtime logs for App').action(function() {
    return cmds["logs"]();
  });

  program.command('revert').description('revert to previous version').action(function() {
    return cmds["revert"]();
  });

  program.command('scale <instances>').description('scale App to number-of-instances').action(function(instances) {
    return cmds["scale"]("" + instances);
  }).on('--help', function() {
    console.log("  Examples:");
    console.log("  $ pm2-meteor scale +2");
    return console.log("  $ pm2-meteor scale 4");
  });

  program.on('--help', function() {
    console.log("  Visit us:");
    console.log("");
    console.log("    http://betawerk.co/");
    return console.log("");
  });

  program.parse(process.argv);

}).call(this);
