// Generated by CoffeeScript 1.10.0
(function() {
  var nodemiral, session;

  nodemiral = require('nodemiral');

  session = nodemiral.session('betawerk.co', {
    username: "root",
    password: "root@betawerk2015"
  });

  session.execute('uname -a', function(err, code, logs) {
    return console.log(logs.stdout);
  });

}).call(this);
